project:
  type: book
  output-dir: _book
  pre-render:
    - Rscript _pre-render.R

book:
  title: "sconjoint: Structural Deep Learning for Conjoint Experiments"
  author: "Avidit Acharya, Jens Hainmueller, Yiqing Xu"
  chapters:
    - index.qmd
    - 01-installation.qmd
    - 02-example-sw.qmd
    - 03-example-gs.qmd
    - 04-simulation.qmd
    - 05-plot-options.qmd
    - 06-faq.qmd

format:
  html:
    theme: cosmo
    toc: true

execute:
  freeze: auto
  cache: true
  eval: true
  echo: true
  warning: false
  message: false
