project:
  type: book
  output-dir: _book
  pre-render:
    - Rscript _pre-render.R

book:
  title: "sconjoint: Structural Deep Learning for Conjoint Experiments"
  chapters:
    - index.qmd
    - 01-installation.qmd
    - 02-sanity-check.qmd
    - 03-example-gs.qmd
    - 04-example-br.qmd
    - 05-example-sw.qmd
    - 06-example-bs.qmd
    - 07-plot-options.qmd
    - 08-advanced-options.qmd
    - references.qmd
    - changelog.qmd

bibliography: references.bib
link-citations: true

nocite: |
  @*

format:
  html:
    theme: cosmo
    toc: true

execute:
  freeze: false
  cache: true
  eval: true
  echo: true
  warning: false
  message: false
